# Generated by Django 2.2.7 on 2019-11-15 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='belongsto',
            options={'verbose_name_plural': 'Schools/Companies'},
        ),
        migrations.RemoveField(
            model_name='menu',
            name='is_breakfast',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='is_dinner',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='is_lunch',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='is_one_dish',
        ),
        migrations.AddField(
            model_name='menu',
            name='time',
            field=models.CharField(choices=[('BREAKFAST', 'BREAKFAST'), ('LUNCH', 'LUNCH'), ('DINNER', 'DINNER')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='cafeteria',
            name='belongs_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafeterias', to='api.BelongsTo'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='liker_set',
            field=models.ManyToManyField(blank=True, related_name='liked_dish_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='menu',
            name='cafeteria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menus', to='api.Cafeteria'),
        ),
        migrations.AlterField(
            model_name='review',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.Dish'),
        ),
        migrations.AlterField(
            model_name='review',
            name='liker_set',
            field=models.ManyToManyField(blank=True, related_name='liked_review_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='written_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
