# Generated by Django 2.2.7 on 2019-11-17 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='menu',
            new_name='menus',
        ),
    ]
