# Generated by Django 2.2.7 on 2019-12-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='recent_date',
        ),
        migrations.AlterField(
            model_name='dish',
            name='frequency',
            field=models.IntegerField(default=1),
        ),
    ]
