# Generated by Django 2.2.7 on 2019-11-15 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191115_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='is_wished',
        ),
        migrations.AddField(
            model_name='dish',
            name='rating_sum',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dish',
            name='count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='written_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='api.Dish')),
                ('wished_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.Dish')),
                ('rated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to=settings.AUTH_USER_MODEL)),
                ('review', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating', to='api.Review')),
            ],
        ),
    ]
