# Generated by Django 2.2.7 on 2019-11-29 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191130_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='dish',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.Dish'),
            preserve_default=False,
        ),
    ]
