# Generated by Django 2.2.7 on 2019-11-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191116_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='rating_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dish',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
